backend:
  name: git-gateway
  repo: lei2rock/blog
  branch: src # Branch to update (master by default)

media_folder: "source/images" # Folder path where uploaded files should be saved, relative to the base of the repo.
public_folder: "/images" # Folder path where uploaded files will be accessed, relative to the base of the built site.

publish_mode: editorial_workflow
site_url: https://blog.dlzhang.com
display_url: https://blog.dlzhang.com
logo_url: /cloud/img/cms-logo.svg
show_preview_links: true
# slug:
#   encoding: "ascii" # default: unicode
#   clean_accents: true
#   sanitize_replacement: "_"  # default: "-"


collections: # A list of collections the CMS should be able to edit
  - name: "bookmovie" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "书影拾光机" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/书影拾光机" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["书影拾光机"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "sticky", widget: "number", default: 0, valueType: "int", min: 0, step: 1}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "academic" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "学术不神秘" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/学术不神秘" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["学术不神秘"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "sticky", widget: "number", default: 0, valueType: "int", min: 0, step: 1}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "notes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "生活随手记" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/生活随手记" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["生活随手记"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "sticky", widget: "number", default: 0, valueType: "int", min: 0, step: 1}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "ramble" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "碎碎念不停" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/碎碎念不停" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["碎碎念不停"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "sticky", widget: "number", default: 0, valueType: "int", min: 0, step: 1}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "pages"
    label: "页面设置"
    files:
      - name: "about"
        label: "关于更多"
        file: "/source/about/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "photos"
        label: "光影留痕"
        file: "/source/about/photos/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "类型", name: "type", widget: "string", default: "picture"}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "share"
        label: "好物分享"
        file: "/source/about/share/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "friends"
        label: "小伙伴们"
        file: "/source/about/friends/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "site"
        label: "本站概览"
        file: "/source/about/site/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "readme"
        label: "README"
        file: "/README.md"
        fields:
          - {label: "正文", name: "body", widget: "markdown"}
